import React from "react";
import { render, screen } from "@testing-library/react";
import RootLayout, { metadata } from "./layout";

vi.mock("next/font/google", () => ({
  __esModule: true,
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
}));

vi.mock("@/components/providers/session-provider", () => ({
  __esModule: true,
  default: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="mock-session-provider">{children}</div>
  ),
}));

vi.mock("next-intl", () => ({
  __esModule: true,
  NextIntlClientProvider: ({ children }: { children: React.ReactNode }) => (
    <div data-testid="mock-intl-provider">{children}</div>
  ),
}));

describe("RootLayout", () => {
  it("должен содержать правильный metadata", () => {
    expect(metadata.title).toBe("REST Client");
    expect(metadata.description).toBe("Generated by create next app");
  });

  it("должен рендерить children", () => {
    render(
      <RootLayout>
        <div data-testid="child">Hello</div>
      </RootLayout>
    );

    expect(screen.getByTestId("child")).toBeInTheDocument();
  });

  it("оборачивает в NextIntlClientProvider и Providers", () => {
    render(
      <RootLayout>
        <div data-testid="child">Hello</div>
      </RootLayout>
    );

    expect(screen.getByTestId("mock-intl-provider")).toBeInTheDocument();
    expect(screen.getByTestId("mock-session-provider")).toBeInTheDocument();
  });
});
